echo-enabled: false
echo-my-name: "MAIN"
echo-passcode: null
echo-recipients: ["127.0.0.1:19132"]

local-chat-distance: 50
local-chat-only: false

loudspeaker-enabled: false
loudspeaker-cost: 10